# -*- coding: utf-8 -*-
"""TREDENCE_INTERNSHIP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPljlexy34PapcoR-GQL66Z4-lzgjwqe
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("using device:", device)

input_size = 32*32*3
hidden_size1 = 512
hidden_size2 = 256
num_classes = 10
batch_size = 64
learning_rate = 0.001
num_epochs = 10
lambda_values = [0.0, 0.00001, 0.0001, 0.001, 0.01]
sparsity_threshold = 1e-2

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5),
                         (0.5, 0.5, 0.5))
])

train_dataset = datasets.CIFAR10(
    root = "./data",
    train =  True,
    transform =  transform,
    download=True
)
test_dataset = datasets.CIFAR10(
    root = "./data",
    train =  False,
    transform =  transform,
    download=True
)
train_loader = DataLoader(
    dataset = train_dataset,
    batch_size=batch_size,
    shuffle = True)

test_loader = DataLoader(
    dataset = test_dataset,
    batch_size=batch_size,
    shuffle = False)

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super(PrunableLinear, self).__init__()

        self.in_features = in_features
        self.out_features = out_features

        self.weight = nn.Parameter(torch.randn(out_features,in_features)*0.01)
        self.bias = nn.Parameter(torch.zeros(out_features))
        self.gate_scores = nn.Parameter(torch.randn(out_features, in_features)*0.01)

    def forward(self,x):
         gates = torch.sigmoid(self.gate_scores)
         pruned_weight = self.weight * gates
         output = torch.matmul(x,pruned_weight.t()) + self.bias
         return output

class FeedForwardNN(nn.Module):
    def __init__(self, input_size, hidden_size1, hidden_size2, num_classes):
        super(FeedForwardNN, self).__init__()

        self.network = nn.Sequential(
        nn.Flatten(),
        PrunableLinear(input_size, hidden_size1),
        nn.ReLU(),
        PrunableLinear(hidden_size1, hidden_size2),
        nn.ReLU(),
        PrunableLinear(hidden_size2, num_classes))

    def forward(self, x):
        return self.network(x)

model = FeedForwardNN(input_size, hidden_size1, hidden_size2, num_classes).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = learning_rate)

def compute_sparsity_loss(model):
    sparsity_loss = 0.0

    for module in model.modules():
        if isinstance(module, PrunableLinear):
            gates = torch.sigmoid(module.gate_scores)
            sparsity_loss += gates.sum()
    return sparsity_loss

def train_one_epoch(model, loader, criterion, optimizer, device,lambda_sparse):
    model.train()
    running_total_loss = 0.0
    running_classification_loss = 0.0
    running_sparsity_loss = 0.0
    correct = 0
    total=0

    for images, labels in loader:
        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        classification_loss = criterion(outputs, labels)
        sparsity_loss = compute_sparsity_loss(model)
        total_loss = classification_loss + lambda_sparse*sparsity_loss

        optimizer.zero_grad()
        total_loss.backward()
        optimizer.step()

        running_total_loss += total_loss.item()
        running_classification_loss += classification_loss.item()
        running_sparsity_loss += sparsity_loss.item()

        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    epoch_total_loss = running_total_loss/len(loader)
    epoch_classification_loss = running_classification_loss/len(loader)
    epoch_sparsity_loss = running_sparsity_loss/len(loader)
    epoch_accuracy = 100*correct/total

    return epoch_total_loss, epoch_classification_loss, epoch_sparsity_loss, epoch_accuracy

def evaluate(model, loader, criterion, device):
    model.eval()

    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item()

            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    epoch_loss = running_loss/len(loader)
    epoch_accuracy = 100*correct/total

    return epoch_loss, epoch_accuracy

def compute_sparsity(model, threshold = 1e-2):
    total_gates = 0
    pruned_gates = 0

    for module in model.modules():
        if isinstance(module, PrunableLinear):
            gates = torch.sigmoid(module.gate_scores)

            total_gates += gates.numel()
            pruned_gates += (gates < threshold).sum().item()
    sparsity_percent = 100.0*pruned_gates/total_gates
    return sparsity_percent

def compute_test_accuracy(model, loader, device):
    model.eval()

    correct=0
    total =0

    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)
            _, predicted =  torch.max(outputs, 1)

            total = total + labels.size(0)
            correct += (predicted == labels).sum().item()
    accuracy = 100.0*correct/total
    return accuracy

results = []
for lambda_sparse in lambda_values:
    print(f"\nTraining with lambda = {lambda_sparse}")
    model = FeedForwardNN(input_size, hidden_size1, hidden_size2, num_classes).to(device)
    optimizer = optim.Adam(model.parameters(), lr = learning_rate)

    for epoch in range(num_epochs):
        train_total_loss, train_cls_loss, train_sparse_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device, lambda_sparse)
        test_loss, test_acc = evaluate(model, test_loader, criterion, device)
        print(f"epoch[{epoch+1}/{num_epochs}]")
        print(f"train loss: {train_total_loss:.4f}")
        print(f"train accuracy: {train_acc:.2f}%")
        print(f"test accuracy: {test_acc:.2f}%")

    final_sparsity = compute_sparsity(model, threshold = sparsity_threshold)
    final_test_accuracy = compute_test_accuracy(model, test_loader, device)
    results.append({"lambda":lambda_sparse, "accuracy":final_test_accuracy, "sparsity":final_sparsity})

print("\n")
print("="*60)
print("final results")
print("="*60)
print(f"{'Lambda':<15}"
      f"{'Accuracy(%)':<20}"
      f"{'Sparsity (%)':<20}")
print("-" * 60)
for result in results:
    print(f"{result['lambda']:<15}"
          f"{result['accuracy']:<20.2f}"
          f"{result['sparsity']:<20.2f}")

all_gates = []
for module in model.modules():
  if isinstance(module, PrunableLinear):
    gates = torch.sigmoid(module.gate_scores)
    gates = (gates.detach().cpu().numpy())
    all_gates.extend(gates.flatten())

plt.figure(figsize = (8, 5))
plt.hist(all_gates, bins = 200, range=(0.007, 0.011))
plt.axvline(x = sparsity_threshold, linestyle = '--', label = 'threshold')
plt.xlabel("gate values")
plt.ylabel("frequency")
plt.title("histogram of the gate values after training")
plt.grid(True)
plt.show()

